#!/bin/bash
import sqlite3


#init or reset
def reset():
	conn = sqlite3.connect('example.db')
	c = conn.cursor()
	c.execute('''CREATE TABLE users (id integer PRIMARY KEY, uname text UNIQUE,  )''')
	c.execute('''CREATE TABLE lang (id integer PRIMARY KEY, lang text UNIQUE )''')
	c.execute('''CREATE TABLE terms (id integer PRIMARY KEY, term text UNIQUE )''')
	c.execute('''CREATE TABLE term-variation (termid integer, varid integer)''')
	c.execute('''CREATE TABLE term_variation (termid integer, varid integer)''')
	c.execute('''CREATE TABLE term_stem (termid integer, stemid integer)''')
	c.execute('''CREATE TABLE term_equiv (termid integer, equivid integer)''')
	c.execute('''CREATE TABLE equiv_vote (termid integer, equivid integer, userid integer, vtype integer)''')
	c.execute('''CREATE TABLE vote_type (id integer, vtype text)''')

	users = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
             ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
             ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
            ]
	
	c.executemany('INSERT INTO users VALUES (?,?,?,?,?)', purchases)

	conn.commit()
	conn.close()

#user or setuser
def login(i):
	#input a number?
	write_file('./current_user',1)
def mywords():
	pass

def word(wrd):
	#shows all suggestions and thier votes

def word(word,vtype):
#	...

#def sources(wrd):


#main
	dict

